### ISSUE TITLE
Launching MPI examples

### ISSUE THREAD

**Issue by davidherreroperez** [ddemidov/amgcl#113]
Hi!

I'm testing the example located at examples/mpi/mpi_amg.cpp using mpich 3.3.1 with different MPI tasks as follows:

```
$ mpirun -np 1 ./mpi_amg
World size: 1
Type:             BiCGStab
Unknowns:         2097152
Memory footprint: 112.00 M

Number of levels:    4
Operator complexity: 1.62
Grid complexity:     1.13

level     unknowns       nonzeros
    0      2097152       14581760 (61.61%) [1]
    1       263552        7918340 (33.46%) [1]
    2        16128        1114704 ( 4.71%) [1]
    3          789          53055 ( 0.22%) [1]

Iterations: 10
Error:      2.50965e-09

[Profile:        **2.010** s] (100.00%)
[ self:          0.044 s] (  2.18%)
[  assemble:     0.185 s] (  9.20%)
[  setup:        0.641 s] ( 31.88%)
[  solve:        1.140 s] ( 56.74%)
```

```
$ mpirun -np 2 ./mpi_amg
World size: 2
Type:             BiCGStab
Unknowns:         1048576
Memory footprint: 56.00 M

Number of levels:    4
Operator complexity: 1.62
Grid complexity:     1.13

level     unknowns       nonzeros
    0      2097152       14581760 (61.77%) [2]
    1       262218        7879732 (33.38%) [2]
    2        15984        1099814 ( 4.66%) [2]
    3          742          47076 ( 0.20%) [2]

Iterations: 11
Error:      4.70781e-09

[Profile:        **8.064** s] (100.00%)
[ self:          0.047 s] (  0.58%)
[  assemble:     0.097 s] (  1.20%)
[  setup:        1.210 s] ( 15.01%)
[  solve:        6.710 s] ( 83.21%)
```

It seems that the size of the problem (unknowns) is divided by two using 2 processes and the assemble stage is reduced by such an order of magnitude, but the setup and solve stages are meaningfully increased. What am I doing wrong?

**Comment by ddemidov** [comment]
Hi!

> It seems that the size of the problem (unknowns) is divided by two using 2 processes

That is only in the output for the bicgstab solver (the same code is used both for shared-memory and distributed-memory solvers, so it outputs the number of variables on the master process). If you look at the number of unknowns at the zero-th level of the amg hierarchy below, the number of unknowns stays the same for both runs.

> but the setup and solve stages are meaningfully increased

I would check two things: first, that you have compiled the examples with optimization enabled (either Release or RelWithDebInfo build configuration in cmake). Second, and more probable, I would run the benchmarks with environment variable `OMP_NUM_THREADS` set to 1 (or at least to number of cores in the system divided by two). Otherwise, you are oversubscribing the CPU, as in the second run both MPI processes use all available CPU cores.

Also, for mpi=1 some tasks (like partitioning) are skipped and so the setup is cheaper.

**Comment by davidherreroperez** [comment]
Thanks for your comments and also for this nice library, the results using environment variable OMP_NUM_THREADS=1 are consistent with computational resources.
