### ISSUE TITLE
Unhandled expection flag occurs during preconditioning 

### ISSUE THREAD

**Issue by salahgaffar** [ddemidov/amgcl#128]
First of all, thank you for the great library and for your previous response to my questions. 
Currently, I am using AMGCL to solve a 2million x  2million matrix with around 11 million nonzero elements. The following unhandled exception occurs in util.hpp during preconditioning with me when I make the tolerance too low and set the maximum levels to a high number. Also, when I decrease the maximum levels, it seems to work fine and no exception occurs. Can you tell me what's the problem with it?

![unhandled exception](https://user-images.githubusercontent.com/34171873/68718936-5fa2a180-05b3-11ea-9f2d-3360c401a06c.PNG)

**Comment by salahgaffar** [comment]
Attached here is the matrix file, a solution for it by another library and a code that reads the two files and passes them to AMGCL library with settings that have proven optimal for my specific type of problem

link:
-------
https://drive.google.com/drive/folders/1xhbVKCgfx16rGnklu3LsjPO7q6qbhsmE?usp=sharing

**Comment by ddemidov** [comment]
The exception thrown from `precondition` id thrown intentionally. It means there is something went wrong during solution of your system. It is not unhandled, it is for you to handle (or rather to acknowledge and decide how to change either your system or the method). We need to see what the message is to decide what to do next.

**Comment by ddemidov** [comment]
> Also, when I decrease the maximum levels, it seems to work fine and no exception occurs.

If I had to guess without seeing the exception message, I would say the exception originates from this line:

https://github.com/ddemidov/amgcl/blob/37339f2b4fe3918a3a47d75832d2bc12206a330e/amgcl/solver/skyline_lu.hpp#L302

which means you have a singular system. Sometimes this is normal (for example, when you have Neumann conditions and the solution is defined up to an additive constant). When you reduce the maximum levels, amgcl is using a couple of smoother iterations instead of direct solve (because it thinks the system is still too large for a direct solve).
You can reproduce this without reducing maximum number of levels by setting [`precond.direct_coarse=false`](https://github.com/ddemidov/amgcl/blob/37339f2b4fe3918a3a47d75832d2bc12206a330e/amgcl/amg.hpp#L113-L118).
