### ISSUE TITLE
Question about structured systems

### ISSUE THREAD

**Issue by timmyL17** [ddemidov/amgcl#15]
Hi,

I am working on solving a system of FEM equations with a few constraints, formulated as a KKT system
```
[ K  C^T ]   [ u       ]   =   [ f   ]
[ C   0  ]   [  lambda ]       [   0 ]
```
From what I can tell, this can be done with AMG if separate smoothing/restriction operators are used for the primal variables and for the lagrange multipliers. See

http://crd.lbl.gov/assets/Uploads/ANAG/adamskktamg.pdf

Would there be an easy way to incorporate this into amgcl? I don't know the code well enough yet to know whether I can reuse the existing smoothers/restriction for the system matrix, then just add my own simple one for the constraints.

Thanks!

**Comment by ddemidov** [comment]
Hi,

A coarsening scheme in amgcl is a [struct](https://github.com/ddemidov/amgcl/blob/be7734ffb2438c3d8b95866c10e866777cbc5bc0/amgcl/coarsening/smoothed_aggregation.hpp#L54) with arbitrary [parameters](https://github.com/ddemidov/amgcl/blob/be7734ffb2438c3d8b95866c10e866777cbc5bc0/amgcl/coarsening/smoothed_aggregation.hpp#L58) that provides [transfer_operators](https://github.com/ddemidov/amgcl/blob/be7734ffb2438c3d8b95866c10e866777cbc5bc0/amgcl/coarsening/smoothed_aggregation.hpp#L103-L105) method. The method should take a system matrix and return a restriction and a prolongation matrices.

A relaxation scheme is another [struct](https://github.com/ddemidov/amgcl/blob/be7734ffb2438c3d8b95866c10e866777cbc5bc0/amgcl/relaxation/damped_jacobi.hpp#L53-L54) with custom [parameters](https://github.com/ddemidov/amgcl/blob/be7734ffb2438c3d8b95866c10e866777cbc5bc0/amgcl/relaxation/damped_jacobi.hpp#L56) that allows to do [pre](https://github.com/ddemidov/amgcl/blob/be7734ffb2438c3d8b95866c10e866777cbc5bc0/amgcl/relaxation/damped_jacobi.hpp#L97-L98) and [post](https://github.com/ddemidov/amgcl/blob/be7734ffb2438c3d8b95866c10e866777cbc5bc0/amgcl/relaxation/damped_jacobi.hpp#L114-L118) relaxation (smoothing).

I think that the approach described in the paper you referenced could be implemented by providing custom versions of coarsening and relaxation schemes, but I don't think I would be able to implement and test this, since I have no experience with KKT systems. If you are willing to do this yourself though, I would be glad to help you navigating the code.

**Comment by timmyL17** [comment]
Thanks, I'll let you know if I have any further questions.
