### ISSUE TITLE
The applicability for periodic problem

### ISSUE THREAD

**Issue by DOUBLE-1024** [ddemidov/amgcl#197]
Hello,Denis
    I want to use the AMGCL to solve a 3D poisson equation(n*n*n) with periodic boundary condition.
    When I construct the coefficient matrix A, I put the nonzero coefficient into the vector _col_ and _val_ just as the example case. For example, for the equation of point(1,1,1),the col number of seven nonzero coefficient is 
(idx-n^2+n^3),   (idx-n+n^2),   (idx-1+n),  idx,  (idx+1),  (idx+n),  (idx+n^2).               [ idx=1]
    Although the residual of the equations decresed to a quite small level, the result is much different from the exact solution in this way.
    What else I should do to solve this kind of periodic problem after I set the value and col number of all the nonzero element?
    Sorry to bother you.
Best Regards!

**Comment by ddemidov** [comment]
Poisson problem with periodic boundary conditions should result in a singular system. More precisely, the solution should not be unique but should be defined up to an additive constant. You could try to pin the solution by adding a single point with a Dirichlet condition for example, but that usually results in bad convergence. Another option is to modify the CG solver so that it forces the solution to have zero mean after each iteration so that the solution is unique (this not implemented in amgcl at the moment).

**Comment by DOUBLE-1024** [comment]
I am much obliged to you for reminding me that the solution is not unique. I used bicgstab to solve the period poisson equation before. The solution depends on the initial value of iteration, and the value at the boundary is right the initial value. But when I used AMGCL, the relationship between the inital value and the solution is not clear. Fortunately, what I conerned is the gradient of the variable, and the gradients of different solutions are the same.
Many thanks for your great help!
Best Regards!
