### ISSUE TITLE
Parallel solves with OpenCL backend

### ISSUE THREAD

**Issue by dokotor** [ddemidov/amgcl#209]
I wanted to know whether it is possible to run several solves in parallel, if they will all fit in GPU memory.

The use case is as follows - there are around 40 solves, each one of them takes around 10 seconds. I have been using a custom CG solver written in CUDA, where I could run e.g. 10 such solves in parallel.

After switching to AMGCL, I am receiving kernel exceptions about type redefinition, when several solves are trying to be run from different threads. I am using OpenCL backend. 

To simplify the use case, let's assume I am running Structural problem tutorial in an OpenMP loop 4 at once.

**Comment by ddemidov** [comment]
GPU backends in amgcl utilize the complete GPU during the solve, and have multiple synchronization points (inner product computations) during each solve, so running the solves in parallel should be ineffective.

I guess you could look into OpenCL device fission if your device supports it to represent your device as multiple virtual devices, and run your solves on those, but I have not tested this approach.

Another option would be to represent multiple systems as a bigger block-diagonal matrix so that the solution of this bigger system gives you the solutions of the smaller ones. But, if you are solving the same system, this would be memory-inefficient (and probably slower anyway due to reading the same matrix multiple times).

What you really need I guess is solving for multiple RHS represented as an NxM dense matrix, but this is not currently possible in amgcl.

**Comment by dokotor** [comment]
Ok, thanks for the response.
