### ISSUE TITLE
Passing Matrix Information from Eigen in MPI Parallel

### ISSUE THREAD

**Issue by dwatanabee** [ddemidov/amgcl#220]
Hello,

I am trying to introduce amgcl into a distributed memory parallel FEM code I am currently working on using [Eigen](https://eigen.tuxfamily.org/index.php?title=Main_Page). Prior to that, I made a very simple sample code as follows and tried to compute it, referring to the tutorial (I wrote it assuming 2 processes).

https://gist.github.com/dwatanabee/bba0902321c02da21d99705473ae1aaf

This code is for solving a unit matrix of dimension 5, but it does not work with the following error

 what(): Zero sum in skyline_lu factorization

I am not sure if the problem is in the program implementation or in the problem setup itself. This may be a rudimentary question, but thank you in advance.

**Comment by dwatanabee** [comment]
The following code written for one process seems to work well.

https://gist.github.com/dwatanabee/f3206a6a3e2fc622b6d792327c835f9f

**Comment by ddemidov** [comment]
The is a couple of problems with your distributed code:

1. The matrix should be cut into continuous strips of rows and passed to the amgcl constructor. The rows should be numbered locally (starting from 0 on each MPI process), and the columns should be numbered globally. So in your example the MPI process 0 should have a 3x5 matrix with elements (0,0), (1,1), and (2,2), and the MPI process 1 should have a 2x5 matrix with elements (0,3) and (0,4). See https://gist.github.com/ddemidov/1a02fab65b70e26cba321e25b7ed21b4 where this is fixed.
2. Your chunk computation in lines 52-54 seems to be wrong to me. row_beg would be 0 and 1 instead of 0 and 3.
3. You should be able to `#include <amgcl/adapter/eigen.hpp>` and construct the amgcl distributed matrix directly from the Eigen one, as shown below, but this does not work because of the next problem.
```cpp
auto A = std::make_shared<amgcl::mpi::distributed_matrix<DBackend>>( world, eA);
```

The next problem looks like a bug in Eigen::SparseMatrix implementation. The `outerIndexPtr()` is filled with zeros, see the output of [lines 59-64](https://gist.github.com/ddemidov/1a02fab65b70e26cba321e25b7ed21b4#file-test_amgcl_mpi-cpp-L59-L64) in my version.

When I form the ptr, col, and val vectors directly, I am getting the correct answer, see the code here:
https://gist.github.com/ddemidov/d75805b8f6759b7e059e2d650dcba588.

**Comment by ddemidov** [comment]
Sorry, it has been some time since I worked with Eigen matrices. There is no bug in Eigen implementation, the problem is that the default storage scheme in Eigen is ColMajor, but amgcl only supports the RowMajor storage scheme. This code works for me:
https://gist.github.com/ddemidov/d74c5178b4a618e5bc195e3e50c77f8a

If you main application only works with ColMajor matrices, you will need to transpose the matrix and copy it to the RowMajor format.

**Comment by ddemidov** [comment]
There is a similar problem with your serial example, but you have been lucky since your matrix is diagonal and so the result does not depend on the storage format.

**Comment by dwatanabee** [comment]
>> 1. The matrix should be cut into continuous strips of rows and passed to the amgcl constructor. The rows should be numbered locally (starting from 0 on each MPI process), and the columns should be numbered globally. So in your example the MPI process 0 should have a 3x5 matrix with elements (0,0), (1,1), and (2,2), and the MPI process 1 should have a 2x5 matrix with elements (0,3) and (0,4). 

Am I correct that multiple processes cannot share the same matrix elements during solver procedure?


>> https://gist.github.com/ddemidov/d74c5178b4a618e5bc195e3e50c77f8a

Thank you very much!
I didn't think it could be implemented so simply.

**Comment by ddemidov** [comment]
> Am I correct that multiple processes cannot share the same matrix elements during solver procedure?

yes, each row should belong to a single process.

**Comment by dwatanabee** [comment]
I got it. Thank you!
