### ISSUE TITLE
possible "fix" to avoid small_vector when unavailable

### ISSUE THREAD

**Issue by RiccardoRossi** [ddemidov/amgcl#61]
Hi @ddemidov i tried to make a PR but the system does not allow.

i am attaching here the file with minimal modifications (using numa_vector instead of small_vector)

[builtin.hpp.zip](https://github.com/ddemidov/amgcl/files/1580575/builtin.hpp.zip)

i should say that i have the feeling that not everything is fixed, since the result still depends on the number of processors, however the PR is still valid

**Comment by ddemidov** [comment]
Thanks! This looks good, however I would replace `numa_vector` with `std::vector`. `numa_vector` has additional overhead of extra omp block in intialization, complete with its own barrier. Also, the final summation is done on the main thread with `std::accumulate`, and anyway, I don't think NUMA would have the necessary granularity (single value per thread, 8 bytes in case of `double`).

> the result still depends on the number of processors

I think that is expected. The result should be stable on the same number of processors, however.

> i tried to make a PR but the system does not allow.

You need to fork the repo, clone your fork and push the changes there, then open PR here. I can wait for you to do this, so that github recognizes you as contributor :)

**Comment by RiccardoRossi** [comment]
i @ddemidov thanks for the courtesy. I did the PR (even though i don't think i will make history with a 3 lines "fix" :-D)

what is strange to me is that unpreconditioned bicgstab, or bigcstab with ilu0 do not fail on the test matrix (kratos implementation, which is copied from Saad's book)

**Comment by ddemidov** [comment]
Thanks, I've merged the PR.

> what is strange to me is that unpreconditioned bicgstab, or bigcstab with ilu0 do not fail on the test matrix (kratos implementation, which is copied from Saad's book)

I believe that is just problem-specific. The RHS is zero except for single point, which often results in bicgstab breakdowns. Random initial condition or different RHS do work with the test problem for me.
