### ISSUE TITLE
How to obtain more levels using Aggregation coarsening?

### ISSUE THREAD

**Issue by nburgess3** [ddemidov/amgcl#65]
Hi,

I recently downloaded AMGCL and attempted to apply it as a solver for a 3D elasticity problem using tetrahedral finite-elements.  I've noticed that aggregation coarsening algorithms are very aggressive and typically reduce the number by 2 to 3 orders of magnitude between levels.  I was wondering if anyone could offer any guidance to reduce this to approximately a factor of 8?

Thanks, 
Nick

**Comment by ddemidov** [comment]
Hi Nick,

If I understand correctly, the elasticity problem should result in a system matrix that has block structure, with 3x3 or 4x4 blocks (the latter if you also account for pressure). In this case you have several options:

1. Let amgcl coarsening algorithm know that your problem has block structure by setting parameter `precond.coarsening.aggr.block_size` to 3 or 4.
2. Use block-valued backend. That is, treat matrix values as 3x3 (or 4x4) small statically sized matrices, and the RHS and the solution values as 3x1 (or 4x1) static vectors. You can see an example [here](https://github.com/ddemidov/amgcl/blob/f747d1afc2afa1bdc410afd75698de6cba278e4e/examples/solver.cpp#L65-L136). This should give you similar results as option 1, but should be more effective (mostly due to enhanced cache-locality).
3. You can provide near-null-space vectors (or rigid body modes) for your problem with `precond.coarsening.nullspace` parameter. See [here](https://github.com/ddemidov/amgcl/blob/f747d1afc2afa1bdc410afd75698de6cba278e4e/examples/solver.cpp#L529-L531) for example.

You can easily test these by saving your matrix to the MatrixMarket format (e.g. with [`amgcl::io::mm_write`](https://github.com/ddemidov/amgcl/blob/f747d1afc2afa1bdc410afd75698de6cba278e4e/amgcl/io/mm.hpp#L349-L351)) and using the [`examples/solver`](https://github.com/ddemidov/amgcl/blob/f747d1afc2afa1bdc410afd75698de6cba278e4e/examples/solver.cpp) executable:
```
# Block-valued solve:
./solver -A A.mtx -b3 
# Pointwise coarsening:
./solver -A A.mtx -p precond.coarsening.agg.block_size=3
# Provide near null space vectors in a dense matrix:
./solver -A A.mtx -N N.mtx
```

**Comment by nburgess3** [comment]
Thanks Denis.  I’ll give these options a try and see if they improve our results.

Regards,
Nick

**Comment by NOhs** [comment]
I applied option 2 for my linear elasticity problem and get the following output:

    level     unknowns       nonzeros
    ---------------------------------
        0      1109889       29391131 (83.17%)
        1      62801          5548249 (15.70%)
        2      4256            390150 ( 1.10%)
        3      164               9116 ( 0.03%)

Is this the expected coarsening?

**Comment by ddemidov** [comment]
This looks reasonable to me. What seems to be the problem?

**Comment by NOhs** [comment]
I am trying to compare performance to a different solver I am using atm, and I don't see why it (the other solver) is so much faster. But for this I will open a new issue with more information to not hijack this one.
