### ISSUE TITLE
Poisson problem with KKT conditions

### ISSUE THREAD

**Issue by ikoruk** [ddemidov/amgcl#93]
I'm sure the following code worked for me before, but now reports "Zero aggregates found" when dim is large (all values >3500 that I tested). I noticed that the eigen backend still uses `MappedSparseMatrix` which is deprecated but I wasn't able to debug this so I couldn't find the cause of the issue.

```
  const int dim = 3500;
  Eigen::SparseMatrix<double, Eigen::RowMajor, Eigen::Index> A(dim, dim);
  A.setIdentity();

  typedef amgcl::backend::eigen<double> Backend;

  typedef amgcl::make_solver<
      amgcl::amg<
          Backend,
          amgcl::coarsening::smoothed_aggregation,
          amgcl::relaxation::spai0
          >,
      amgcl::solver::cg<Backend>
      > Solver;

  Solver solve(A);
```

Even if temporary, I would appreciate any hints on how to transform my matrix to work with the builtin or `zero_copy` adapters, as I couldn't get it working for this size of a matrix using those either.

**Comment by ddemidov** [comment]
3500 looks suspiciously close to 3000 here:

https://github.com/ddemidov/amgcl/blob/d1f8387a05ccc409d57505460d5fde27637ce902/amgcl/solver/skyline_lu.hpp#L93-L95

Any matrix below 3000 unknowns is solved directly. Above that amgcl is trying to coarsen the system. I think that you get "Zero aggregates found" because the matrix is a diagonal one, and aggregation fails in this case. This should be reproducible with any backend. Did you try a non-diagonal matrix?

You should be able to use an Eigen sparse matrix directly with a bultin backend (if `<amgcl/backend/builtin.hpp>` is included).

And to use a `zero_copy` adapter, you need to make sure that `_StorageIndex` [in the matrix template parameters](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html) is `ptrdiff_t` (or binary compatible). Then you should be able to use
``cpp`
zero_copy(A.rows(), A.outerIntexPtr(), A.innerIndexPtr(), A.valuePtr())
```

**Comment by ikoruk** [comment]
OK, so this issue is actually irrespective of the backend, and actually depends on the size and content of the matrix. And, as you say, it only happens when amgcl needs to coarsen the system.

I am trying to solve a Poisson system with KKT conditions. When I have no such conditions, the Poisson solve works no matter the size, however when I add these conditions, then the solver works below ~3400 unknowns but fails at anything above, returning nan.

**Comment by ddemidov** [comment]
Again, you can probably solve the smaller matrices because those are solved directly. What is a KKT condition? Can you share the failing matrix (above 3500 unknowns) in MatrixMarket format? You can use `amgcl::io::mm_write()`:

https://github.com/ddemidov/amgcl/blob/d1f8387a05ccc409d57505460d5fde27637ce902/amgcl/io/mm.hpp#L388-L390

**Comment by ikoruk** [comment]
A [KKT condition](https://en.wikipedia.org/wiki/Karush–Kuhn–Tucker_conditions) is basically just a generalization of [Lagrange multipliers](https://en.wikipedia.org/wiki/Lagrange_multiplier), adding some linear constraints to the Poisson solve.
Here is a [failing matrix](https://gist.github.com/ikoruk/2470730d84cae8eab4342887561e318a). It might be that it is poorly conditioned, but I am still able to get results from Eigen's Conjugate Gradient / BiCGSTAB.

**Comment by ddemidov** [comment]
I do get a `Zero diagonal in skyline_lu` with the matrix, which usually means the matrix is singular on the coarse level, and I can not solve it with an unpreconditioned bicgstab (either with amgcl or scipy, see below). Did you check the residual you get from an eigen solver? Can you also post the right-hand side you used? ([amgcl::io::mm_write()](https://github.com/ddemidov/amgcl/blob/d1f8387a05ccc409d57505460d5fde27637ce902/amgcl/io/mm.hpp#L354-L361) can write dense arrays).

amgcl:
```cpp
./solver -A failing_matrix.mm -p precond.class=dummy solver.maxiter=10000
Solver
======
Type:             BiCGStab
Unknowns:         3112
Memory footprint: 170.19 K

Preconditioner
==============
identity matrix as preconditioner
  unknowns: 3112
  nonzeros: 51752

Iterations: 10000
Error:      84.9115

[Profile:       1.000 s] (100.00%)
[  reading:     0.048 s] (  4.76%)
[  setup:       0.000 s] (  0.03%)
[  solve:       0.952 s] ( 95.16%)
```

scipy:
```py
In [1]: from numpy import *
In [2]: from scipy.io import mmread
In [3]: from scipy.sparse.linalg import bicgstab
In [4]: A = mmread('failing_matrix.mm')
In [8]: b = ones(A.shape[0])
In [10]: x,info = bicgstab(A, b)
In [11]: info
Out[11]: 31120
In [12]: linalg.norm(b - A * x)
Out[12]: 4046.2759634460326
```

**Comment by ddemidov** [comment]
In fact, even the direct solver fails here:
```
./solver -A failing_matrix.mm -p precond.coarse_enough=5000
Solver
======
Type:             BiCGStab
Unknowns:         3112
Memory footprint: 170.19 K

Preconditioner
==============
Number of levels:    1
Operator complexity: 1.00
Grid complexity:     1.00
Memory footprint:    4.71 M

level     unknowns       nonzeros      memory
---------------------------------------------
    0         3112          51752      4.71 M (100.00%)

Iterations: 100
Error:      1.50965

[Profile:       0.293 s] (100.00%)
[ self:         0.000 s] (  0.16%)
[  reading:     0.048 s] ( 16.49%)
[  setup:       0.026 s] (  8.91%)
[  solve:       0.218 s] ( 74.44%)
```

**Comment by ikoruk** [comment]
Ah, I didn't test this exact matrix with a direct solve, since this is when I was constructing the smallest example matrix I could. But this actually explains it if it's becoming singular at the coarse level. I guess I could fix this by adding a regularizer. Thanks for your help!
